'use strict';

const serverConstants = {
  SGP_API_BASE_PATH: process.env.SGP_API_BASE_PATH,
  //SGP_API_BASE_PATH: 'http://localhost:3001/sgapp/api',

  SAZEN_API_BASE_PATH: process.env.SAZEN_API_BASE_PATH,
  //SAZEN_API_BASE_PATH: 'http://localhost:5001',

  NGO_APP_BASE_PATH: process.env.NGO_APP_BASE_PATH,

  NGO_NOTIFICATION_API_BASE_PATH: process.env.NGO_NOTIFICATION_API_BASE_PATH,
  //NGO_NOTIFICATION_API_BASE_PATH: 'http://localhost:6000/ngo/api/',

  NGO_APP_APIS: {
    EVENT_DETAILS: 'eventdetails',
  },
  SGP_API_REQUEST_APPROVAL: '/ngo/requestApproval',

  NOTIFY_SAZEN_API: '/sgmessages',
  NOTIFICATION_EVENT_CONFIRMATION: 'event/registration/approval',
  NOTIFICATION_VOLUNTEER_COMMUNICATIONS: 'volunteercampaigns/communications',

  SAZEN_ENGAGEMENTS: '/sazenengagements',
  TIME_LOGS: '/timelogs',

  NGO_EVENT_REGISTRATION_STATUS_REGISTERED: 'Registered',
  NGO_EVENT_REGISTRATION_STATUS_APPROVED: 'Approved',
  NGO_EVENT_REGISTRATION_STATUS_CANCELLED: 'Cancelled',
  NGO_EVENT_REGISTRATION_STATUS_REJECT: 'Rejected',

  NGO_VOLUNTEER_CAMPAIGN_REGISTRATION_STATUS_REGISTERED: 'Registered',
  NGO_VOLUNTEER_CAMPAIGN_REGISTRATION_STATUS_APPROVED: 'Approved',
  NGO_VOLUNTEER_CAMPAIGN_REGISTRATION_STATUS_CANCELLED: 'Cancelled',
  NGO_VOLUNTEER_CAMPAIGN_REGISTRATION_STATUS_REJECT: 'Rejected',


  NOTIFICATIONS_SAZEN_EVENTS: {
    EVENT_NOTIFICATION: 'SAZEN_EVENT_NOTIFICATION',
    SAZEN_DONATION_CAMPAIGN_NOTIFICATION: 'SAZEN_DONATION_CAMPAIGN_NOTIFICATION',
  },
  NOTIFICATIONS_NGO_EVENTS: {
    EVENT_NOTIFICATION: 'NGO_EVENT_NOTIFICATION',
    VOLUNTEER_CAMPAIGN_NOTIFICATION: 'VOLUNTEER_CAMPAIGN_NOTIFICATION',
    NGO_DONATION_CAMPAIGN_NOTIFICATION: 'NGO_DONATION_CAMPAIGN_NOTIFICATION',
  },

  NOTIFICATIONS_TYPES: {
    SAZEN_EVENT_APPROVE_NOTIFICATION: 'SAZEN_EVENT_APPROVE_NOTIFICATION',
    SAZEN_EVENT_REGISTRATION_CONFIRMATION_NOTIFICATION:
      'SAZEN_EVENT_REGISTRATION_CONFIRMATION_NOTIFICATION',
    NGO_EVENT_REGISTRATION_CONFIRMATION_NOTIFICATION:
      'NGO_EVENT_REGISTRATION_CONFIRMATION_NOTIFICATION',
    NGO_VOLUNTEER_CAMPAIGN_REGISTRATION_CONFIRMATION_NOTIFICATION:
    'NGO_VOLUNTEER_CAMPAIGN_REGISTRATION_CONFIRMATION_NOTIFICATION',
    NGO_VOLUNTEER_COMMUNICATION: 'NGO_VOLUNTEER_COMMUNICATION',
    SAZEN_VOLUNTEER_CAMPAIGN_REGISTRATION_CONFIRMATION_NOTIFICATION:
    'SAZEN_VOLUNTEER_CAMPAIGN_REGISTRATION_CONFIRMATION_NOTIFICATION',
    SAZEN_VOLUNTEER_CAMPAIGN_WORK_ASSIGNED_NOTIFICATION:
    'SAZEN_VOLUNTEER_CAMPAIGN_WORK_ASSIGNED_NOTIFICATION',
    SAZEN_VOLUNTEER_CAMPAIGN_APPROVE_NOTIFICATION:
    'SAZEN_VOLUNTEER_CAMPAIGN_APPROVE_NOTIFICATION',

    //Donation Notification Types
    NGO_DONATION_CAMPAIGN_PLEDGE_DONATION_CONFIRMATION_NOTIFICATION:
      'NGO_DONATION_CAMPAIGN_PLEDGE_DONATION_CONFIRMATION_NOTIFICATION',
    SAZEN_DONATION_CAMPAIGN_PLEDGE_DONATION_CONFIRMATION_NOTIFICATION:
      'SAZEN_DONATION_CAMPAIGN_PLEDGE_DONATION_CONFIRMATION_NOTIFICATION',
  },
  NOTIFICATION_KIND: {
    EMAIL_NOTIFICATION: 'EMAIL_NOTIFICATION',
    PULL_NOTIFICATION: 'PULL_NOTIFICATION',
    EMAIL: 'EMAIL'
  },

  EVENT_EMITTER: {
    VOLUNTEER_CAMPAIGN_STATE_CHANGE: 'VOLUNTEER_CAMPAIGN_STATE_CHANGE',
    VOLUNTEER_CAMPAIGN_REGISTRATION_COUNT_CHANGE: 'VOLUNTEER_CAMPAIGN_REGISTRATION_COUNT_CHANGE',
  },

  SAZEN_ENGAGEMENT_TYPES: {
    EVENT_ENGAGEMENT: 'EVENT',
    VOLUNTEER_CAMPAIGN_ENGAGEMENT: 'VOLUNTEER_CAMPAIGN',
    DONATION_CAMPAIGN_ENGAGEMENT: 'DONATION_CAMPAIGN_ENGAGEMENT',
  },

  DEFAULT_BANNER: process.env.DEFAULT_BANNER,

};

  module.exports = serverConstants;
