'use strict';


const appConstants = {
  API_RESPONSE_SUCCESS: 'SUCCESS',
  API_RESPONSE_FAIL: 'FAIL',
  API_RESPONSE_STATUS_SUCCESS_CODE: 200,
  PROVIDER_FACEBOOK: 'facebook',
  PROVIDER_GOOGLE: 'google',
  PROVIDER_TWITTER: 'twitter',

  ACTION_DASHBOARD_BUTTON_ACTIVE: 'ACTION_DASHBOARD_BUTTON_ACTIVE',
  ACTION_ACTIVITY_BUTTON_ACTIVE: 'ACTION_ACTIVITY_BUTTON_ACTIVE',
  ACTION_VOLUNTEER_BUTTON_ACTIVE: 'ACTION_VOLUNTEER_BUTTON_ACTIVE',
  ACTION_DONATION_BUTTON_ACTIVE: 'ACTION_DONATION_BUTTON_ACTIVE',
  ACTION_EVENTS_BUTTON_ACTIVE: 'ACTION_EVENTS_BUTTON_ACTIVE',
  ACTION_PROFILE_BUTTON_ACTIVE: 'ACTION_PROFILE_BUTTON_ACTIVE',


  ACTION_PAGE_TITLE_UPDATE: 'ACTION_PAGE_TITLE_UPDATE',
  ACTION_NGO_REGISTER_SUCCESS: 'ACTION_NGO_REGISTER_SUCCESS',
  ACTION_NGO_REGISTER_FAIL: 'ACTION_NGO_REGISTER_FAIL',
  ACTIONN_NGO_FIND_NGO_BY_ADMIN_EMAIL_SUCCESS: 'ACTIONN_NGO_FIND_NGO_BY_ADMIN_EMAIL_SUCCESS',
  ACTIONN_NGO_FIND_NGO_BY_ADMIN_EMAIL_FAIL: 'ACTIONN_NGO_FIND_NGO_BY_ADMIN_EMAIL_FAIL',

  ACTION_USER_UPDATE_SUCCESS: 'ACTION_USER_UPDATE_SUCCESS',
  ACTION_USER_UPDATE_FAIL: 'ACTION_USER_UPDATE_FAIL',
  ACTION_DASHBOARD_USER_LOGIN_SUCCESS: 'ACTION_DASHBOARD_USER_LOGIN_SUCCESS',
  ACTION_DASHBOARD_USER_INFO: 'ACTION_DASHBOARD_USER_INFO',
  ACTION_DASHBOARD_NGO_INFO: 'ACTION_DASHBOARD_NGO_INFO',
  ACTION_NGO_INFO: 'ACTION_NGO_INFO',

  ACTION_FETCH_CAUSES_SUCCESS: 'ACTION_FETCH_CAUSES_SUCCESS',
  ACTION_FETCH_CAUSES_FAIL: 'ACTION_FETCH_CAUSES_FAIL',
  ACTION_UPDATE_NGO_INFO_SUCCESS: 'ACTION_UPDATE_NGO_INFO_SUCCESS',
  ACTION_UPDATE_NGO_INFO_FAIL: 'ACTION_UPDATE_NGO_INFO_FAIL',

  ACTION_SAVE_MICROSITE_SUCCESS: 'ACTION_SAVE_MICROSITE_SUCCESS',
  ACTION_SAVE_MICROSITE_FAIL: 'ACTION_SAVE_MICROSITE_FAIL',
  ACTION_GET_MICROSITE_SUCCESS: 'ACTION_GET_MICROSITE_SUCCESS',
  ACTION_GET_MICROSITE_FAIL: 'ACTION_GET_MICROSITE_FAIL',

  ACTION_GET_NGO_SUCCESS: 'ACTION_FETCH_NGO_SUCCESS',
  ACTION_FETCH_NGO_FAIL: 'ACTION_FETCH_NGO_FAIL',

  ACTION_SAVE_PROFILE_SUCCESS: 'ACTION_SAVE_PROFILE_SUCCESS',
  ACTION_SAVE_PROFILE_FAIL: 'ACTION_SAVE_PROFILE_FAIL',

  ACTION_GET_PROFILE_SUCCESS: 'ACTION_GET_PROFILE_SUCCESS',
  ACTION_GET_PROFILE_FAIL: 'ACTION_GET_PROFILE_FAIL',

  ACTION_CREATE_EVENT_SUCCESS: 'ACTION_CREATE_EVENT_SUCCESS',
  ACTION_CREATE_EVENT_FAIL: 'ACTION_CREATE_EVENT_FAIL',

  ACTION_UPDATE_EVENT_SUCCESS: 'ACTION_UPDATE_EVENT_SUCCESS',
  ACTION_UPDATE_EVENT_FAIL: 'ACTION_UPDATE_EVENT_FAIL',

  ACTION_FETCH_EVENTS_SUCCESS: 'ACTION_FETCH_EVENTS_SUCCESS',
  ACTION_FETCH_EVENTS_FAIL: 'ACTION_FETCH_EVENTS_FAIL',
  ACTION_FETCH_EVENT_DETAILS_SUCCESS: 'ACTION_FETCH_EVENT_DETAILS_SUCCESS',

  ACTION_SELECT_EVENT_TEMPLATE: 'ACTION_SELECT_EVENT_TEMPLATE',
  ACTION_EVENT_UPDATED: 'ACTION_EVENT_UPDATED',
  ACTION_UPDATE_NGO_AND_TEMPLATE_INFO: 'ACTION_UPDATE_NGO_AND_TEMPLATE_INFO',

  ACTION_SELECT_MICROSITE_TEMPLATE: 'ACTION_SELECT_MICROSITE_TEMPLATE',


  ACTION_LOCATION_UPDATE_SUCCESS: 'ACTION_LOCATION_UPDATE_SUCCESS',

  ACTION_FETCH_SUBSCRIPTIONS_SUCCESS: 'ACTION_FETCH_SUBSCRIPTIONS_SUCCESS',
  ACTION_FETCH_SUBSCRIPTIONS_FAIL: 'ACTION_FETCH_SUBSCRIPTIONS_FAIL',

  ACTION_CARD_SELECTED: 'ACTION_CARD_SELECTED',
  ACTION_FONT_SIZE_CHANGED: 'ACTION_FONT_SIZE_CHANGED',
  ACTION_OPTION_SELECTED: 'ACTION_OPTION_SELECTED',
  ACTION_IMAGE_SIZE_CHANGED: 'ACTION_IMAGE_SIZE_CHANGED',
  ACTION_DATE_FORMAT_CHANGED: 'ACTION_DATE_FORMAT_CHANGED',
  ACTION_TIME_FORMAT_CHANGED: 'ACTION_TIME_FORMAT_CHANGED',
  ACTION_CARD_COLLAPSIBLE: 'ACTION_CARD_COLLAPSIBLE',
  ACTION_SHOW_PROGRESS_BAR: 'ACTION_SHOW_PROGRESS_BAR',
  ACTION_HIDE_PROGRESS_BAR: 'ACTION_HIDE_PROGRESS_BAR',
  ACTION_LOCATION_UPDATE: 'ACTION_LOCATION_UPDATE',
  ACTION_CAMPAIGN_SELECT: 'ACTION_CAMPAIGN_SELECT',

  ACTION_FETCH_NOTIFICATION_SUCCESS: 'ACTION_FETCH_NOTIFICATION_SUCCESS',
  ACTION_FETCH_NOTIFICATION_FAIL: 'ACTION_FETCH_NOTIFICATION_FAIL',

  //
  ACTION_CREATE_VOLUNTEER_CAMPAIGN_SUCCESS: 'ACTION_CREATE_VOLUNTEER_CAMPAIGN_SUCCESS',
  ACTION_CREATE_VOLUNTEER_CAMPAIGN_FAIL: 'ACTION_CREATE_VOLUNTEER_CAMPAIGN_FAIL',

  ACTION_UPDATE_VOLUNTEER_CAMPAIGN_SUCCESS: 'ACTION_UPDATE_VOLUNTEER_CAMPAIGN_SUCCESS',
  ACTION_UPDATE_VOLUNTEER_CAMPAIGN_FAIL: 'ACTION_UPDATE_VOLUNTEER_CAMPAIGN_FAIL',
  ACTION_FETCH_VOLUNTEER_CAMPAIGNS_SUCCESS: 'ACTION_FETCH_VOLUNTEER_CAMPAIGNS_SUCCESS',
  ACTION_FETCH_VOLUNTEER_CAMPAIGNS_FAIL: 'ACTION_FETCH_VOLUNTEER_CAMPAIGNS_FAIL',
  ACTION_FETCH_VOLUNTEER_CAMPAIGN_DETAILS_SUCCESS:
    'ACTION_FETCH_VOLUNTEER_CAMPAIGN_DETAILS_SUCCESS',
  ACTION_SELECT_VOLUNTEER_CAMPAIGN_TEMPLATE: 'ACTION_SELECT_VOLUNTEER_CAMPAIGN_TEMPLATE',
  ACTION_VOLUNTEER_CAMPAIGN_UPDATED: 'ACTION_VOLUNTEER_CAMPAIGN_UPDATED',
  //

  // Donation
  ACTION_CREATE_DONATION_CAMPAIGN_SUCCESS: 'ACTION_CREATE_DONATION_CAMPAIGN_SUCCESS',
  ACTION_CREATE_DONATION_CAMPAIGN_FAIL: 'ACTION_CREATE_DONATION_CAMPAIGN_FAIL',

  ACTION_UPDATE_DONATION_CAMPAIGN_SUCCESS: 'ACTION_UPDATE_DONATION_CAMPAIGN_SUCCESS',
  ACTION_UPDATE_DONATION_CAMPAIGN_FAIL: 'ACTION_UPDATE_DONATION_CAMPAIGN_FAIL',
  ACTION_FETCH_DONATION_CAMPAIGNS_SUCCESS: 'ACTION_FETCH_DONATION_CAMPAIGNS_SUCCESS',
  ACTION_FETCH_DONATION_CAMPAIGNS_FAIL: 'ACTION_FETCH_DONATION_CAMPAIGNS_FAIL',
  ACTION_FETCH_DONATION_CAMPAIGN_DETAILS_SUCCESS:
    'ACTION_FETCH_DONATION_CAMPAIGN_DETAILS_SUCCESS',
  ACTION_SELECT_DONATION_CAMPAIGN_TEMPLATE: 'ACTION_SELECT_DONATION_CAMPAIGN_TEMPLATE',
  ACTION_DONATION_CAMPAIGN_UPDATED: 'ACTION_DONATION_CAMPAIGN_UPDATED',
  //

  campaignTypes: {
    generalEventCampaignId: 'GECampaign',
    volunteerCampaignId: 'VOLCampaign',
    donationCampaignId: 'DONCampaign',
  },

  eventRegistrationStatus: {
    Registered: 'Registered',
    Cancelled: 'Cancelled',
    Approved: 'Approved',
    Rejected: 'Rejected',
  },

  volunteerCampaignRegistrationStatus: {
    Registered: 'Registered',
    Cancelled: 'Cancelled',
    Approved: 'Approved',
    Rejected: 'Rejected',
  },

  donationStatus: {
    DONATION_PLEDGED_STATUS: 'DONATION_PLEDGED_STATUS',
    DONATION_ACCEPTED_STATUS: 'DONATION_ACCEPTED_STATUS',
    DONATION_REJECTED_STATUS: 'DONATION_REJECTED_STATUS'
  },

  sgObjectTypes: {
    EVENT_TYPE: 0,
    VOLUNTEER_TYPE: 1,
    DONATION_TYPE: 2,
    EVENT_TYPE_NAME: 'event',
    DONATION_TYPE_NAME: 'donationCampaign'
  },

  ngoStatuses: {
    NEW: 'NEW',
    IN_REVIEW: 'IN_REVIEW',
    ACTIVE: 'ACTIVE',
    REJECTED: 'REJECTED',
    SUSPENDED: 'SUSPENDED',
    BLACK_LISTED: 'BLACK_LISTED',
  },

  requestTypes: {
    PUBLISH: 'PUBLISH',
  },

  facebookAPPId: process.env.FACEBOOK_APP_ID,
};

module.exports = appConstants;
